import { Student } from './types';

export const MOCK_STUDENTS: Student[] = [
  {
    id: '1',
    nickname: '樱桃',
    jid: '165836869',
    followUpStatus: '待跟进',
    lastClassTime: '2026-04-13 16:30:00',
    sceneId: '60000',
    officialAccount: '15220',
    courseName: '少儿编程基础',
    courseStatus: '体验课完课',
    learningProgress: { completed: 2, total: 2 },
    followUpPerson: null,
    followUpTime: null,
    purchaseCount: 1,
    purchaseAmount: 99,
    tags: ['待转化'],
    organization: '机构A',
    project: '项目1',
    notes: []
  },
  {
    id: '2',
    nickname: '钱德勒',
    jid: '147444282',
    followUpStatus: '已跟进',
    lastClassTime: '2026-04-13 16:30:00',
    sceneId: '60000',
    officialAccount: '15220',
    courseName: 'Python进阶',
    courseStatus: '正价课完课',
    learningProgress: { completed: 48, total: 48 },
    followUpPerson: '王琪璐 Jasmine',
    followUpTime: '2026-04-13 11:58:59',
    purchaseCount: 2,
    purchaseAmount: 5999,
    tags: ['优质学员'],
    organization: '机构B',
    project: '项目2',
    notes: [
      {
        id: 'n1',
        stage: '正价课完课',
        content: '学员表现优异，建议推荐进阶课程。',
        time: '2026-04-13 11:58:59',
        operator: '王琪璐 Jasmine'
      }
    ]
  },
  {
    id: '3',
    nickname: '阿加西',
    jid: '161890141',
    followUpStatus: '待跟进',
    lastClassTime: '2026-04-13 17:00:00',
    sceneId: '60000',
    officialAccount: '15220',
    courseName: 'Scratch创意编程',
    courseStatus: '正价课首课',
    learningProgress: { completed: 1, total: 24 },
    followUpPerson: null,
    followUpTime: null,
    purchaseCount: 1,
    purchaseAmount: 2999,
    tags: ['待转化'],
    organization: '机构A',
    project: '项目1',
    notes: []
  },
  {
    id: '4',
    nickname: 'Bernice',
    jid: '136812281',
    followUpStatus: '待跟进',
    lastClassTime: '2026-04-13 17:00:00',
    sceneId: '60000',
    officialAccount: '15220',
    courseName: 'C++算法班',
    courseStatus: '连续缺席三节课',
    learningProgress: { completed: 12, total: 48 },
    followUpPerson: null,
    followUpTime: null,
    purchaseCount: 1,
    purchaseAmount: 4500,
    tags: ['流失预警'],
    organization: '机构C',
    project: '项目3',
    notes: [
      {
        id: 'n2',
        stage: '连续缺席三节课',
        content: '-',
        time: '2026-04-13 17:51:40',
        operator: '王琪璐 Jasmine'
      }
    ]
  },
  {
    id: '5',
    nickname: '家文',
    jid: '166824044',
    followUpStatus: '已跟进',
    lastClassTime: '2026-04-13 18:00:00',
    sceneId: '60000',
    officialAccount: '15220',
    courseName: '人工智能入门',
    courseStatus: '正价课完课',
    learningProgress: { completed: 24, total: 24 },
    followUpPerson: '王琪璐 Jasmine',
    followUpTime: '2026-04-13 14:20:00',
    purchaseCount: 3,
    purchaseAmount: 8800,
    tags: ['待续费'],
    organization: '机构A',
    project: '项目2',
    notes: []
  },
  {
    id: '6',
    nickname: '板子',
    jid: '166860418',
    followUpStatus: '待跟进',
    lastClassTime: '2026-04-13 19:00:00',
    sceneId: '60000',
    officialAccount: '15219',
    courseName: '机器人搭建',
    courseStatus: '已购试听未约课',
    learningProgress: { completed: 0, total: 1 },
    followUpPerson: null,
    followUpTime: null,
    purchaseCount: 1,
    purchaseAmount: 9.9,
    tags: ['待约课'],
    organization: '机构B',
    project: '项目1',
    notes: []
  },
  {
    id: '7',
    nickname: '张三',
    jid: '123456789',
    followUpStatus: '待跟进',
    lastClassTime: '2026-03-10 10:00:00',
    sceneId: '60001',
    officialAccount: '15221',
    courseName: '少儿美术',
    courseStatus: '近30天未约课',
    learningProgress: { completed: 5, total: 20 },
    followUpPerson: null,
    followUpTime: null,
    purchaseCount: 1,
    purchaseAmount: 1500,
    tags: ['沉默学员'],
    organization: '机构C',
    project: '项目2',
    notes: []
  }
];
